#pragma once
#include "int.h"

typedef enum AsmReg {
    ASM_REG_NONE = 0,
    ASM_REG_QAX, ASM_REG_QBX, ASM_REG_QCX, ASM_REG_QDX,
    ASM_REG_QSI, ASM_REG_QDI, ASM_REG_QSP, ASM_REG_QBP,
    ASM_REG_Q8, ASM_REG_Q9, ASM_REG_Q10, ASM_REG_Q11,
    ASM_REG_Q12, ASM_REG_Q13, ASM_REG_Q14, ASM_REG_Q15,
    ASM_REG_QIP,
    ASM_REG_DAX, ASM_REG_DBX, ASM_REG_DCX, ASM_REG_DDX,
    ASM_REG_DSI, ASM_REG_DDI, ASM_REG_DSP, ASM_REG_DBP,
    ASM_REG_Q8D, ASM_REG_Q9D, ASM_REG_Q10D, ASM_REG_Q11D,
    ASM_REG_Q12D, ASM_REG_Q13D, ASM_REG_Q14D, ASM_REG_Q15D,
    ASM_REG_WAX, ASM_REG_WBX, ASM_REG_WCX, ASM_REG_WDX,
    ASM_REG_WSI, ASM_REG_WDI, ASM_REG_WSP, ASM_REG_WBP,
    ASM_REG_Q8W, ASM_REG_Q9W, ASM_REG_Q10W, ASM_REG_Q11W,
    ASM_REG_Q12W, ASM_REG_Q13W, ASM_REG_Q14W, ASM_REG_Q15W,
    ASM_REG_BAL, ASM_REG_BBL, ASM_REG_BCL, ASM_REG_BDL,
    ASM_REG_BAH, ASM_REG_BBH, ASM_REG_BCH, ASM_REG_BDH,
    ASM_REG_BSIL, ASM_REG_BDIL, ASM_REG_BSPL, ASM_REG_BBPL,
    ASM_REG_Q8B, ASM_REG_Q9B, ASM_REG_Q10B, ASM_REG_Q11B,
    ASM_REG_Q12B, ASM_REG_Q13B, ASM_REG_Q14B, ASM_REG_Q15B,
    ASM_REG_XMM0, ASM_REG_XMM1, ASM_REG_XMM2, ASM_REG_XMM3,
    ASM_REG_XMM4, ASM_REG_XMM5, ASM_REG_XMM6, ASM_REG_XMM7,
    ASM_REG_XMM8, ASM_REG_XMM9, ASM_REG_XMM10, ASM_REG_XMM11,
    ASM_REG_XMM12, ASM_REG_XMM13, ASM_REG_XMM14, ASM_REG_XMM15,
    ASM_REG_YMM0, ASM_REG_YMM1, ASM_REG_YMM2, ASM_REG_YMM3,
    ASM_REG_YMM4, ASM_REG_YMM5, ASM_REG_YMM6, ASM_REG_YMM7,
    ASM_REG_YMM8, ASM_REG_YMM9, ASM_REG_YMM10, ASM_REG_YMM11,
    ASM_REG_YMM12, ASM_REG_YMM13, ASM_REG_YMM14, ASM_REG_YMM15,
    ASM_REG_ST0, ASM_REG_ST1, ASM_REG_ST2, ASM_REG_ST3,
    ASM_REG_ST4, ASM_REG_ST5, ASM_REG_ST6, ASM_REG_ST7,
    ASM_REG_CR0, ASM_REG_CR2, ASM_REG_CR3, ASM_REG_CR4, ASM_REG_CR8,
    ASM_REG_DR0, ASM_REG_DR1, ASM_REG_DR2, ASM_REG_DR3,
    ASM_REG_DR6, ASM_REG_DR7
} AsmReg;

typedef enum AsmOp {
    ASM_OP_NONE = 0,
    ASM_OP_MOVQ, ASM_OP_MOVD, ASM_OP_MOVW, ASM_OP_MOVB,
    ASM_OP_MOVZX, ASM_OP_MOVSX,
    ASM_OP_LEAQ, ASM_OP_LEAD, ASM_OP_LEAW, ASM_OP_LEAB,
    ASM_OP_PUSHQ, ASM_OP_PUSHD, ASM_OP_PUSHW, ASM_OP_PUSHB,
    ASM_OP_POPQ, ASM_OP_POPD, ASM_OP_POPW, ASM_OP_POPB,
    ASM_OP_XCHGQ, ASM_OP_XCHGD, ASM_OP_XCHGW, ASM_OP_XCHGB,
    ASM_OP_ADDQ, ASM_OP_ADDD, ASM_OP_ADDW, ASM_OP_ADDB,
    ASM_OP_SUBQ, ASM_OP_SUBD, ASM_OP_SUBW, ASM_OP_SUBB,
    ASM_OP_IMULQ, ASM_OP_IMULD, ASM_OP_IMULW, ASM_OP_IMULB,
    ASM_OP_MULQ, ASM_OP_MULD, ASM_OP_MULW, ASM_OP_MULB,
    ASM_OP_IDIVQ, ASM_OP_IDIVD, ASM_OP_IDIVW, ASM_OP_IDIVB,
    ASM_OP_DIVQ, ASM_OP_DIVD, ASM_OP_DIVW, ASM_OP_DIVB,
    ASM_OP_INCQ, ASM_OP_INCD, ASM_OP_INCW, ASM_OP_INCB,
    ASM_OP_DECQ, ASM_OP_DECD, ASM_OP_DECW, ASM_OP_DECB,
    ASM_OP_NEGQ, ASM_OP_NEGD, ASM_OP_NEGW, ASM_OP_NEGB,
    ASM_OP_CMPQ, ASM_OP_CMPD, ASM_OP_CMPW, ASM_OP_CMPB,
    ASM_OP_TESTQ, ASM_OP_TESTD, ASM_OP_TESTW, ASM_OP_TESTB,
    ASM_OP_ANDQ, ASM_OP_ANDD, ASM_OP_ANDW, ASM_OP_ANDB,
    ASM_OP_ORQ, ASM_OP_ORD, ASM_OP_ORW, ASM_OP_ORB,
    ASM_OP_XORQ, ASM_OP_XORD, ASM_OP_XORW, ASM_OP_XORB,
    ASM_OP_NOTQ, ASM_OP_NOTD, ASM_OP_NOTW, ASM_OP_NOTB,
    ASM_OP_SHLQ, ASM_OP_SHLD, ASM_OP_SHLW, ASM_OP_SHLB,
    ASM_OP_SHRQ, ASM_OP_SHRD, ASM_OP_SHRW, ASM_OP_SHRB,
    ASM_OP_SARQ, ASM_OP_SARD, ASM_OP_SARW, ASM_OP_SARB,
    ASM_OP_SALQ, ASM_OP_SALD, ASM_OP_SALW, ASM_OP_SALB,
    ASM_OP_BTQ, ASM_OP_BTD, ASM_OP_BTW, ASM_OP_BTB,
    ASM_OP_BTSQ, ASM_OP_BTSD, ASM_OP_BTSW, ASM_OP_BTSB,
    ASM_OP_BTRQ, ASM_OP_BTRD, ASM_OP_BTRW, ASM_OP_BTRB,
    ASM_OP_BTCQ, ASM_OP_BTCD, ASM_OP_BTCW, ASM_OP_BTCB,
    ASM_OP_BSFQ, ASM_OP_BSFD, ASM_OP_BSFW, ASM_OP_BSFB,
    ASM_OP_BSRQ, ASM_OP_BSRD, ASM_OP_BSRW, ASM_OP_BSRB,
    ASM_OP_POPCNTQ, ASM_OP_POPCNTD, ASM_OP_POPCNTW, ASM_OP_POPCNTB,
    ASM_OP_LZCNTQ, ASM_OP_LZCNTD, ASM_OP_LZCNTW, ASM_OP_LZCNTB,
    ASM_OP_TZCNTQ, ASM_OP_TZCNTD, ASM_OP_TZCNTW, ASM_OP_TZCNTB,
    ASM_OP_JMP, ASM_OP_JZ, ASM_OP_JNZ, ASM_OP_JE, ASM_OP_JNE,
    ASM_OP_JL, ASM_OP_JG, ASM_OP_JLE, ASM_OP_JGE,
    ASM_OP_JB, ASM_OP_JA, ASM_OP_JBE, ASM_OP_JAE,
    ASM_OP_JC, ASM_OP_JNC, ASM_OP_JO, ASM_OP_JNO,
    ASM_OP_JS, ASM_OP_JNS, ASM_OP_JP, ASM_OP_JNP,
    ASM_OP_JECXZ, ASM_OP_JRCXZ,
    ASM_OP_CALL, ASM_OP_RET,
    ASM_OP_NOP, ASM_OP_HLT, ASM_OP_CPUID, ASM_OP_INT,
    ASM_OP_CLI, ASM_OP_STI, ASM_OP_IRETQ,
    ASM_OP_INVLPG, ASM_OP_WBINVD, ASM_OP_RDMSR, ASM_OP_WRMSR,
    ASM_OP_RDTSC, ASM_OP_RDTSCP, ASM_OP_SWAPGS,
    ASM_OP_LGDT, ASM_OP_LIDT, ASM_OP_SGDT, ASM_OP_SIDT,
    ASM_OP_LLDT, ASM_OP_LTR, ASM_OP_SLDT, ASM_OP_STR,
    ASM_OP_INB, ASM_OP_INW, ASM_OP_IND,
    ASM_OP_OUTB, ASM_OP_OUTW, ASM_OP_OUTD,
    ASM_OP_PAUSE, ASM_OP_MFENCE, ASM_OP_LFENCE, ASM_OP_SFENCE,
    ASM_OP_XADDQ, ASM_OP_XADDD, ASM_OP_XADDW, ASM_OP_XADDB,
    ASM_OP_CMPXCHGQ, ASM_OP_CMPXCHGD, ASM_OP_CMPXCHGW, ASM_OP_CMPXCHGB,
    ASM_OP_REP_MOVSB, ASM_OP_REP_MOVSW, ASM_OP_REP_MOVSD, ASM_OP_REP_MOVSQ,
    ASM_OP_REP_STOSB, ASM_OP_REP_STOSW, ASM_OP_REP_STOSD, ASM_OP_REP_STOSQ,
    ASM_OP_REP_LODSB, ASM_OP_REP_LODSW, ASM_OP_REP_LODSD, ASM_OP_REP_LODSQ,
    ASM_OP_REP_CMPSB, ASM_OP_REP_CMPSW, ASM_OP_REP_CMPSD, ASM_OP_REP_CMPSQ,
    ASM_OP_REP_SCASB, ASM_OP_REP_SCASW, ASM_OP_REP_SCASD, ASM_OP_REP_SCASQ,
    ASM_OP_REPNE_MOVSB, ASM_OP_REPNE_MOVSW, ASM_OP_REPNE_MOVSD, ASM_OP_REPNE_MOVSQ,
    ASM_OP_REPNE_STOSB, ASM_OP_REPNE_STOSW, ASM_OP_REPNE_STOSD, ASM_OP_REPNE_STOSQ,
    ASM_OP_REPNE_LODSB, ASM_OP_REPNE_LODSW, ASM_OP_REPNE_LODSD, ASM_OP_REPNE_LODSQ,
    ASM_OP_REPNE_CMPSB, ASM_OP_REPNE_CMPSW, ASM_OP_REPNE_CMPSD, ASM_OP_REPNE_CMPSQ,
    ASM_OP_REPNE_SCASB, ASM_OP_REPNE_SCASW, ASM_OP_REPNE_SCASD, ASM_OP_REPNE_SCASQ,
    ASM_OP_REPZ_MOVSB, ASM_OP_REPZ_MOVSW, ASM_OP_REPZ_MOVSD, ASM_OP_REPZ_MOVSQ,
    ASM_OP_REPZ_STOSB, ASM_OP_REPZ_STOSW, ASM_OP_REPZ_STOSD, ASM_OP_REPZ_STOSQ,
    ASM_OP_REPZ_LODSB, ASM_OP_REPZ_LODSW, ASM_OP_REPZ_LODSD, ASM_OP_REPZ_LODSQ,
    ASM_OP_REPZ_CMPSB, ASM_OP_REPZ_CMPSW, ASM_OP_REPZ_CMPSD, ASM_OP_REPZ_CMPSQ,
    ASM_OP_REPZ_SCASB, ASM_OP_REPZ_SCASW, ASM_OP_REPZ_SCASD, ASM_OP_REPZ_SCASQ,
    ASM_OP_SSE_MOVAPS, ASM_OP_SSE_MOVUPS, ASM_OP_SSE_MOVSS, ASM_OP_SSE_MOVSD,
    ASM_OP_SSE_MOVDQA, ASM_OP_SSE_MOVDQU,
    ASM_OP_SSE_ADDPS, ASM_OP_SSE_ADDPD, ASM_OP_SSE_ADDSS, ASM_OP_SSE_ADDSD,
    ASM_OP_SSE_SUBPS, ASM_OP_SSE_SUBPD, ASM_OP_SSE_SUBSS, ASM_OP_SSE_SUBSD,
    ASM_OP_SSE_MULPS, ASM_OP_SSE_MULPD, ASM_OP_SSE_MULSS, ASM_OP_SSE_MULSD,
    ASM_OP_SSE_DIVPS, ASM_OP_SSE_DIVPD, ASM_OP_SSE_DIVSS, ASM_OP_SSE_DIVSD,
    ASM_OP_SSE_SQRTPS, ASM_OP_SSE_SQRTPD, ASM_OP_SSE_SQRTSS, ASM_OP_SSE_SQRTSD,
    ASM_OP_SSE_MINPS, ASM_OP_SSE_MINPD, ASM_OP_SSE_MAXPS, ASM_OP_SSE_MAXPD,
    ASM_OP_SSE_ANDPS, ASM_OP_SSE_ANDPD, ASM_OP_SSE_ORPS, ASM_OP_SSE_ORPD,
    ASM_OP_SSE_XORPS, ASM_OP_SSE_XORPD,
    ASM_OP_SSE_PXOR, ASM_OP_SSE_PAND, ASM_OP_SSE_POR, ASM_OP_SSE_PANDN,
    ASM_OP_SSE_CMPPS, ASM_OP_SSE_CMPPD, ASM_OP_SSE_CMPSS, ASM_OP_SSE_CMPSD,
    ASM_OP_SSE_COMISS, ASM_OP_SSE_COMISD, ASM_OP_SSE_UCOMISS, ASM_OP_SSE_UCOMISD,
    ASM_OP_SSE_CVTSI2SS, ASM_OP_SSE_CVTSI2SD,
    ASM_OP_SSE_CVTSS2SI, ASM_OP_SSE_CVTSD2SI,
    ASM_OP_SSE_CVTPS2PD, ASM_OP_SSE_CVTPD2PS,
    ASM_OP_SSE_CVTSS2SD, ASM_OP_SSE_CVTSD2SS,
    ASM_OP_AVX_VMOVAPS, ASM_OP_AVX_VMOVUPS, ASM_OP_AVX_VMOVSS, ASM_OP_AVX_VMOVSD,
    ASM_OP_AVX_VMOVDQA, ASM_OP_AVX_VMOVDQU,
    ASM_OP_AVX_VADDPS, ASM_OP_AVX_VADDPD, ASM_OP_AVX_VADDSS, ASM_OP_AVX_VADDSD,
    ASM_OP_AVX_VSUBPS, ASM_OP_AVX_VSUBPD, ASM_OP_AVX_VSUBSS, ASM_OP_AVX_VSUBSD,
    ASM_OP_AVX_VMULPS, ASM_OP_AVX_VMULPD, ASM_OP_AVX_VMULSS, ASM_OP_AVX_VMULSD,
    ASM_OP_AVX_VDIVPS, ASM_OP_AVX_VDIVPD, ASM_OP_AVX_VDIVSS, ASM_OP_AVX_VDIVSD,
    ASM_OP_AVX_VSQRTPS, ASM_OP_AVX_VSQRTPD,
    ASM_OP_AVX_VANDPS, ASM_OP_AVX_VANDPD, ASM_OP_AVX_VORPS, ASM_OP_AVX_VORPD,
    ASM_OP_AVX_VXORPS, ASM_OP_AVX_VXORPD,
    ASM_OP_AVX_VPXOR, ASM_OP_AVX_VPAND, ASM_OP_AVX_VPOR,
    ASM_OP_AVX_VZEROUPPER, ASM_OP_AVX_VZEROALL
} AsmOp;

typedef struct AsmEntry {
    const char* rwszName;
    U64 rwullOp;
} AsmEntry;

typedef struct AsmRegEntry {
    const char* rwszName;
    U64 rwullReg;
} AsmRegEntry;

U64 AsmOpLookup(const char* rwszName);
U64 AsmRegLookup(const char* rwszName);
const char* AsmOpName(U64 rwullOp);
const char* AsmRegName(U64 rwullReg);
int AsmRegIsGPR(U64 rwullReg);
int AsmRegIs64(U64 rwullReg);
int AsmRegIs32(U64 rwullReg);
int AsmRegIs16(U64 rwullReg);
int AsmRegIs8(U64 rwullReg);
int AsmRegIsXMM(U64 rwullReg);
int AsmRegIsYMM(U64 rwullReg);
int AsmRegIsST(U64 rwullReg);
int AsmRegIsCR(U64 rwullReg);
int AsmRegIsDR(U64 rwullReg);
U64 AsmRegLow3(U64 rwullReg);
int AsmRegNeedsRex(U64 rwullReg);
U64 AsmRegRexBit(U64 rwullReg);
